nohup: ignoring input
Watching for file changes with StatReloader
[17/Jul/2020 10:28:35] "GET / HTTP/1.1" 200 8220
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 252, in send_preamble
    self._write(('HTTP/%s %s\r\n' % (self.http_version,self.status)).encode('iso-8859-1'))
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[17/Jul/2020 10:28:35] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('61.135.6.131', 60839)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 252, in send_preamble
    self._write(('HTTP/%s %s\r\n' % (self.http_version,self.status)).encode('iso-8859-1'))
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 119, in handle_error
    super().handle_error()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 197, in handle_one_request
    handler.run(self.server.get_app())
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[17/Jul/2020 10:28:44] "GET / HTTP/1.1" 200 8220
[17/Jul/2020 10:28:50] "GET / HTTP/1.1" 200 8220
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 252, in send_preamble
    self._write(('HTTP/%s %s\r\n' % (self.http_version,self.status)).encode('iso-8859-1'))
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[17/Jul/2020 10:28:50] "GET / HTTP/1.1" 500 59
----------------------------------------
Exception happened during processing of request from ('61.135.6.131', 60840)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 332, in send_headers
    self.send_preamble()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 252, in send_preamble
    self._write(('HTTP/%s %s\r\n' % (self.http_version,self.status)).encode('iso-8859-1'))
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 453, in _write
    result = self.stdout.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 775, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 119, in handle_error
    super().handle_error()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 639, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/ubuntu/anaconda3/lib/python3.6/socketserver.py", line 696, in __init__
    self.handle()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 172, in handle
    self.handle_one_request()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 197, in handle_one_request
    handler.run(self.server.get_app())
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 114, in close
    super().close()
  File "/home/ubuntu/anaconda3/lib/python3.6/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
----------------------------------------
[17/Jul/2020 10:28:54] "GET / HTTP/1.1" 200 8220
